### ISSUE TITLE
Example files how to add include_domains and other parameters?

### ISSUE THREAD

**Issue by kattapug** [tavily-ai/tavily-python#6]
Hi 

This is interesting and just started playing around with it.

Quick question I am struggling to see which part of the code section to change to use the below parameters for the example files.   Company Information.py and OpenAI Assistant.py. I would like to do some testing to understand how it works.

{
  "api_key": "your api key",
  "query": "your search query",
  "search_depth": "basic",
  "include_answer": false,
  "include_images": true,
  "include_raw_content": false,
  "max_results": 5,
  "include_domains": [],
  "exclude_domains": []
}

Thanks

**Comment by assafelovic** [comment]
Hey @kattapug ! You can simply use the search method like this:
`
from tavily import TavilyClient
tavily = TavilyClient(api_key="YOUR_API_KEY")
# Call the search method with your params:
tavily.search(query="your search query", search_depth="basic", include_answer=False, include_images=True, max_results=5)
`
In the example above I'm ignoring the last two params since they already default to empty list behind the scenes. 
Feel free to checkout the documentation here: https://docs.tavily.com/docs/tavily-api/introduction

**Comment by karrtikiyer-tw** [comment]
Thanks @assafelovic , can you share an example to pass multiple include domains, we tried passing , multiple comma separated values but did not seem to work

**Comment by kattapug** [comment]
Hi 

Testing the below code.

from tavily import TavilyClient
tavily = TavilyClient(api_key="tvly-xxxxxxxxxxxx")
# Call the search method with your params:
tavily.search(query="Should I invest in Apple right now?", search_depth="basic", include_answer=False, include_images=True, max_results=5)

Error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[c:\Dev\sima\tavily.py](file:///C:/Dev/sima/tavily.py) in line 1
----> [1](file:///c%3A/Dev/sima/tavily.py?line=0) from tavily import TavilyClient
      [2](file:///c%3A/Dev/sima/tavily.py?line=1) tavily = TavilyClient(api_key="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")
      [3](file:///c%3A/Dev/sima/tavily.py?line=2) # Call the search method with your params:

File [c:\Dev\sima\tavily.py:1](file:///C:/Dev/sima/tavily.py:1)
----> [1](file:///c%3A/Dev/sima/tavily.py?line=0) from tavily import TavilyClient
      [2](file:///c%3A/Dev/sima/tavily.py?line=1) tavily = TavilyClient(api_key="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")
      [3](file:///c%3A/Dev/sima/tavily.py?line=2) # Call the search method with your params:

ImportError: cannot import name 'TavilyClient' from partially initialized module 'tavily' (most likely due to a circular import) (c:\Dev\sima\tavily.py)

Any suggestion how to fix this.

**Comment by Wambugu-Muchemi** [comment]
> Thanks @assafelovic , can you share an example to pass multiple include domains, we tried passing , multiple comma separated values but did not seem to work

@karrtikiyer-tw Hello, currently facing this issue as well, did you find a way to make it work?

**Comment by Wambugu-Muchemi** [comment]
> Hi
> 
> Testing the below code.
> 
> from tavily import TavilyClient tavily = TavilyClient(api_key="tvly-xxxxxxxxxxxx")
> 
> # Call the search method with your params:
> tavily.search(query="Should I invest in Apple right now?", search_depth="basic", include_answer=False, include_images=True, max_results=5)
> 
> ## Error
> ImportError Traceback (most recent call last) c:\Dev\sima\tavily.py in line 1 ----> 1 from tavily import TavilyClient 2 tavily = TavilyClient(api_key="tvly-xxxxx") 3 # Call the search method with your params:
> 
> File c:\Dev\sima\tavily.py:1 ----> 1 from tavily import TavilyClient 2 tavily = TavilyClient(api_key="tvly-xxxx") 3 # Call the search method with your params:
> 
> ImportError: cannot import name 'TavilyClient' from partially initialized module 'tavily' (most likely due to a circular import) (c:\Dev\sima\tavily.py)
> 
> Any suggestion how to fix this.

@kattapug The circular import error is being caused by your file name which is similar to the `from tavily import TavilyClient`. Rename your python file name from tavily.py to something else like tavily_test.py.

**Comment by beschmitt** [comment]
As a follow-up to this:
Currently my understanding is that passing a domain to the Include_domain param sets it so Tavily will EXCLUSIVELY check the passed domains for the information.
Is there any way to tell Tavily that it should always check these domains but if it doesn't find relevant information it should check other domains as well? I'm currently passing a domain of a company and asking who the architect of the Statue of Liberty is but it only checks the domain of the company instead of for example wikipedia.
